### ISSUE TITLE
Allow namespaced variable in ask

### ISSUE THREAD

**Issue by yelvert** [andrewvaughan/ansible-prompt#82]
With the following task:
```yaml
- prompt:
    msg:
      say: Whats up?
      ask: some_namespace.some_variable
```

I would expect the `some_namespace.some_variable` to be set, but instead I get the following error:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Invalid character in 'ask' parameter 'some_namespace.some_variable'."}
```

I have also tried it with `some_namespace["some_variable"]` and `some_namespace['some_variable']` with the same error.
